### ISSUE TITLE
Copy Image to Local Ramdisk or Storage

### ISSUE THREAD

**Issue by bensallen** [jlowellwofford/imageapi#20] opened 2021-03-01 22:50 UTC
Add support to copy an RBD image, NFS squashfs file, etc from network storage to local ramdisk or node local storage, then loop mount and overlay as normal.

This will be useful for cases where an admin doesn't want the node to have a hard dependency on the network storage being up, and doesn't care about the increased boot time and load.

**Comment by jlowellwofford** [comment] 2021-07-26 04:05
Duplicate of #16

**Closed as completed by jlowellwofford** 2021-07-26 04:05 UTC
Labels: enhancement
